# Generated by Django 3.0.8 on 2020-08-18 15:33

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source_file',
            name='file',
            field=models.FileField(upload_to=api.models.user_directory_path),
        ),
    ]
