# Generated by Django 3.0.8 on 2020-08-18 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200818_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='source_file',
            name='parent_repository',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.repository'),
        ),
    ]
