# Generated by Django 3.0.8 on 2020-08-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_source_file_parent_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='source_files', to='api.source_file'),
        ),
    ]
