# Generated by Django 3.0.8 on 2020-08-18 16:19

import api.models
import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200818_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source_file',
            name='file',
            field=models.FileField(upload_to=api.models.user_directory_path, validators=[api.validators.max_file_size]),
        ),
    ]
