# Generated by Django 3.0.8 on 2020-08-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200818_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='public',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
