# Generated by Django 3.0.8 on 2020-08-19 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200818_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
