# Generated by Django 3.0.8 on 2020-08-19 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_repository_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source_file',
            name='parent_repository',
        ),
    ]
